### ISSUE TITLE
Rebasing the repo on pyscaffold-dsproject 

### ISSUE THREAD

**Issue by LeviBorodenko** [oliviermirat/MyAIGuide#2]
Hey everyone,

I have made many good experiences with setting up larger-scale (python) code bases using a tool called [Pyscaffold](https://github.com/pyscaffold/pyscaffoldext-dsproject). In particular, it offers a fantastic clean and functional folder structure for data science projects and has many best practises build into it. I.e. requirements management, auto generated docs, code formatters etc. pp.

I would suggest that I losslessly port the existing code and data into such a project structure in a PR today or tomorrow and that we go from there.

Best,
Levi

**Comment by oliviermirat** [comment]
Hi Levi,

Sure, that sounds like a great idea to me!

Let me know when your PR is ready :).

Olivier

**Comment by LeviBorodenko** [comment]
TODO:

- [ ] Fix broken references inside the READMEs.
- [ ] Unzip raw data.
- [ ] Move Conda stuff into reference folder.
- [ ] Explain pyscaffold to team.

**Comment by oliviermirat** [comment]
I fixed the links in the READMEs.

**Comment by LeviBorodenko** [comment]
Already, I think everything is setup. Time to do some actual data science :P
