### ISSUE TITLE
Create a function that returns the elevation for a set of GPS points (lattitude, longitude)

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/MyAIGuide#20]
We will need to use that function afterward to calculate the elevation gain for participant 1 and 2.

**Comment by LeviBorodenko** [comment]
On it!

**Comment by LeviBorodenko** [comment]
What will be the format of the input data and the exact use case? 
The function will most likely require to make a request to a public api for each query which would be a lot quicker if we give the function a list of coordinates and not just one pair of coordinates at a time. So it would be good to know how exactly the function will be used, so one can design accordingly.

**Comment by oliviermirat** [comment]
For the most part, the input data will look something like this:
https://github.com/oliviermirat/MyAIGuide/blob/master/data/raw/ParticipantData/Participant1PublicOM/GoogleFitData/smartphone2/Activities/2019-03-11T23_40_21%2B07_00_PT19M49S_Walking.tcx

We might also try to use some data that looks like this:
https://github.com/oliviermirat/MyAIGuide/blob/master/data/raw/ParticipantData/Participant1PublicOM/MovesAppData/daily/places/places_20171121.csv
Or like this: https://github.com/oliviermirat/MyAIGuide/blob/master/data/raw/ParticipantData/Participant1PublicOM/MovesAppData/yearly/places/places_2017.csv

(For these two sources, the data will mostly be coming from Participant 1 and 2)

It's not sure yet but we might also try to use some data from GPS logger: see the confidential repo for Participant 1.
