### ISSUE TITLE
Missing data part 1: create a function that converts a dataframe into an excel file

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/MyAIGuide#21]
This function must take as an input the dataframe of a participant, a beginning date, an end date, and a list of dataframe columns to export to the excel file.
We will send that excel file to the participant to fill the blanks, then we will import the new data into the dataframe.
To simplify things for the participant, it would be good if all the values could be in bold, and the blank field not in bold: that way, when the participant fills a blank the value inputed is not the bold, while all the other values are (that way the participants can easily see what he inputed and what was already there, as he's filling in the dataframe).

**Comment by evadatinez** [comment]
on it :)

**Comment by evadatinez** [comment]
what could be the right folder to export the excel file into it?

**Comment by oliviermirat** [comment]
I think that exporting it in the current folder is fine.
Then after the user fills it and sends it back to us, I think we should store it inside data/raw.
