### ISSUE TITLE
Missing data part 2: Add values inside the dataframe of a participant based on excel file

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/MyAIGuide#22]
This requires issue #21 to have been solved.
Once we get the excel file back from the participant, we will want to add the values inputed by the participant back into the dataframe.
So we must create a function that takes as an input a dataframe and an excel file and adds the new values into the dataframe. We also want to keep track of which values where inputed by the participant and which ones are new. In order to do that, we should: for any column "nameColumn" of the dataframe, create a new column called "nameColumn_ManualFill" and fill that newly created column with the values inside the excel file (we should also make sure that the values originally present in the dataframe have not been changed by the participant).

**Comment by evadatinez** [comment]
on it

**Comment by evadatinez** [comment]
Quick question! For the test function I want to save an excel file simulating manually filled data by a participant. Where would it be a good place to keep it?

**Comment by oliviermirat** [comment]
One option would be to create a new folder called for instance "excelFilesForMissingDataFill" inside the folder data/raw and put the test excel file inside that new folder.

**Comment by evadatinez** [comment]
sounds good to me, thank you! :)
