### ISSUE TITLE
Calculate cumulated elevation gain for physical activities recorded by GoogleFit

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/MyAIGuide#27]
To solve this issue, you will need to use the solution proposed in issue #20 to get the elevation from GPS coordinates.
The aim is to calculate the cumulated elevation gain for physical activities recorded by Google Fit for Participant 1 and Participant 2.
For Participant 1, you can find the data here: https://github.com/oliviermirat/MyAIGuide/blob/master/data/raw/ParticipantData/Participant1PublicOM/GoogleFitData
For Participant 2, the data is in the confidential repo.
(for both participants, the "Activité"/"Activitie" folders seem to have the most information)

**Comment by LeviBorodenko** [comment]
On it!

**Comment by LeviBorodenko** [comment]
Could you clarify what the following columns measure inside the GoogleFit data:

- 'Basse latitude (°)', 'Basse longitude (°)', 'Haute latitude (°)', 'Haute longitude (°)', 
- 'Poids moyen (kg)', 'Poids maximal (kg)', 'Poids minimal (kg)',
- 'Durée de l'activité "Marche à pied" (ms)', 'Durée de l'activité "Course à pied" (ms)'

Cheers :)

**Comment by oliviermirat** [comment]
This would translate to:
- 'Low Latitude', 'Low Longitude", 'High Latitude', 'High Longitude'
-'Mean Weight", "Maximum Weight', 'Minimum Weight'
-'Duration of the activity "Walk', 'Duration of the activity 'Running'
I'm not sure what the "low" and "high" mean for the "latitude" and "longitude", but there's probably some logic behind that.
For Participant 1, it's in French for smartphone 1, and in English for smartphone 2. For Participant 2, it think it should all be in English.
Thanks a lot :)

**Comment by LeviBorodenko** [comment]
Thanks!
I do wonder what high and low lat long mean. Does it refer to highest and lowest elevation during the exercise? Because that would be very useful for calculating elevation changes.

**Comment by oliviermirat** [comment]
I'm just noticing now that you're looking at the dailyAggregation subfolder: in those csv files, the high and low might refer to the beginning and end of the period represented in that line of the csv file, or something like that.
But I was thinking that the Activités subfolder might contain more precise information. But I'm not sure, some investigation is needed here.

**Comment by LeviBorodenko** [comment]
How do we define _cumulated elevation gain_?

**Comment by oliviermirat** [comment]
Wikipedia gives a nice definition of cumulated elevation gain: https://en.wikipedia.org/wiki/Cumulative_elevation_gain . Let me know if it doesn't make sense.

**Comment by LeviBorodenko** [comment]
turns out that a coord to elevation function is not even needed for this issue, as the raw data contains elevation information.

**Comment by LeviBorodenko** [comment]
I think this issue is solved. We know have a function that takes a folder containing .tcx files and the master dataframe and it updates the dataframe with (daily) elevation gains/losses and calories due to GoogleFit exercises.
