### ISSUE TITLE
Extract elevation gain for GPSlogger files

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/MyAIGuide#32]
Create a function that extracts the elevation gain from GPSlogger files (in the private repo). Use it to place the elevation gain inside the dataframe for Participant 1. The GPSlogger files contain elevation data at each time point so this should be easier than what we had to do in the previous GPS elevation issues. More GPSlogger files will be added for Participant 1 afterward in the private repo.
This issue is less urgent than the issue 31.

**Comment by LeviBorodenko** [comment]
We now have a function that adds the elevation gains from the GPSlogger files to a master df given a folder containing .gpx files.

This issue should thus be resolved.

**Comment by oliviermirat** [comment]
Great!
