### ISSUE TITLE
Decide of a good data input format for Google Map API to get the elevation

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/MyAIGuide#37]
Once you have a format in mind, please check that this input format is ok with everyone.

**Comment by LeviBorodenko** [comment]
Taking a look at the [documentation](https://developers.google.com/maps/documentation/elevation/intro), we see that the Google Elevation API requires a comma-separated coordinate text string.
I would suggest that the _coordinates to elevations_ function takes either
1. A list of lat, lon tuples or
2. A dataframe with 'lat', lon' columns.

and it then returns a dataframe of elevations for each point.

**Comment by LeviBorodenko** [comment]
I have gone with a list of lat, lon tuples for now. But this can be trivially extended to other formats later on.

**Comment by ann-w** [comment]
Yes that is fine with me!
