### ISSUE TITLE
Create a script similar to the one created in issue 51, but while taking into account the missing data adjustments

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/MyAIGuide#54]
After issue 52 is done, we will send the excel file to Participant 2 who will fill it in to adjust for the missing data.
In this issue, we must use the excel file sent back by Participant 2 to adjust for the missing data, then store and plot the data as we did in issue 51.

**Comment by evadatinez** [comment]
Just to remark that I believe the function `manualDataImport` from the following script would be useful here to import the data https://github.com/oliviermirat/MyAIGuide/blob/master/src/MyAIGuide/data/manualDataImport.py

**Comment by oliviermirat** [comment]
@evadatinez : yes, exactly. Thanks for specifying that.
