### ISSUE TITLE
Manually check data saved in dataframe for Participant 3, 4, 5, 6, 7, 9

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/MyAIGuide#64]
Just a quick issue (should take about 20 minutes):

Use the scripts 1_createDataFrameParticipant_3_4_5_6_7_9.py and 2_plotParticipantData_3_4_5_6_7_9.py to plot the data for Participants 3, 4, 5, 6, 7 and 9.

Go back to the raw data and manually check the correspondence for a few arbitrarily chosen values: this is just a quick manual sanity check, it shouldn't take more than 20 minutes (if it takes more, it's that you're checking too many values :)).

**Comment by d4nielmeyer** [comment]
Picked out around 15 values. All of them matched with the corresponding raw data.
