### ISSUE TITLE
Create function to retrieve mental state data and store it in a dataframe (for participant 8 mostly)

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/MyAIGuide#9]

**Comment by evadatinez** [comment]
@oliviermirat 
is it this data -> https://github.com/oliviermirat/MyAIGuide/blob/master/data/raw/ParticipantData/Participant8Anonymized/Participant8Observations.csv ?

**Comment by oliviermirat** [comment]
Actually, I was just about to close this issue as it is already being taken care of by issue #8. https://github.com/oliviermirat/MyAIGuide/blob/master/data/raw/ParticipantData/Participant8Anonymized/Participant8Observations.csv is for the issue #11 .
